// RSS 2.0 changelog feed of a walkthrough's takes. Each take is one item:
// the director's verdict as the description, the master URL as the link.
// Mintlify-parity for `<Update>` components — Foley already tracks
// versioned takes; this just exposes them in a syndication-friendly shape.

import "server-only";
import { NextResponse } from "next/server";
import { isValidWalkthroughId } from "@/lib/ids";
import { listTakes, loadWalkthrough } from "@/lib/fs";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/'/g, "&apos;")
    .replace(/"/g, "&quot;");
}

function dashboardBase(req: Request): string {
  const env =
    process.env.NEXT_PUBLIC_DASHBOARD_URL ?? process.env.PUBLIC_DASHBOARD_URL;
  if (env) return env.replace(/\/$/, "");
  try {
    const u = new URL(req.url);
    return `${u.protocol}//${u.host}`;
  } catch {
    return "http://localhost:3000";
  }
}

export async function GET(
  req: Request,
  { params }: { params: { id: string } },
) {
  if (!isValidWalkthroughId(params.id)) {
    return NextResponse.json({ error: "invalid_id" }, { status: 400 });
  }

  let walkthrough;
  try {
    walkthrough = await loadWalkthrough(params.id);
  } catch {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }
  const takes = await listTakes(params.id);
  const base = dashboardBase(req);
  const product = walkthrough.target_app.repo.split("/")[1] ?? params.id;

  const sorted = takes
    .slice()
    .sort((a, b) => b.created_at.localeCompare(a.created_at));

  const items = sorted
    .map((t) => {
      const counts: Record<string, number> = {};
      for (const d of t.step_diffs ?? []) {
        const k = String(d.status);
        counts[k] = (counts[k] ?? 0) + 1;
      }
      const summary = Object.entries(counts)
        .map(([k, v]) => `${v} ${k}`)
        .join(", ");
      const description =
        (t.director_note ?? "") +
        (summary ? ` — ${summary}` : "") +
        (t.pr_number ? ` (PR #${t.pr_number})` : "");
      const compareUrl =
        t.id === "master"
          ? `${base}/takes/master`
          : `${base}/takes/${t.id}/compare/master`;
      const pubDate = new Date(t.created_at).toUTCString();
      return [
        "    <item>",
        `      <title>${escapeXml(t.id)}${t.pr_title ? `: ${escapeXml(t.pr_title)}` : ""}</title>`,
        `      <link>${escapeXml(compareUrl)}</link>`,
        `      <guid isPermaLink="false">${escapeXml(`${params.id}/${t.id}`)}</guid>`,
        `      <pubDate>${pubDate}</pubDate>`,
        `      <category>${escapeXml(t.status ?? "ready")}</category>`,
        `      <description>${escapeXml(description.trim() || `Take ${t.id} for ${product}.`)}</description>`,
        "    </item>",
      ].join("\n");
    })
    .join("\n");

  const channelLink = `${base}/walkthroughs/${params.id}`;
  const lastBuild = sorted[0]?.created_at
    ? new Date(sorted[0].created_at).toUTCString()
    : new Date().toUTCString();

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n` +
    "  <channel>\n" +
    `    <title>${escapeXml(`${product} walkthrough · changelog`)}</title>\n` +
    `    <link>${escapeXml(channelLink)}</link>\n` +
    `    <description>${escapeXml(`Versioned takes of the ${product} walkthrough, in reverse chronological order. Auto-generated by Foley from GitHub PR activity.`)}</description>\n` +
    `    <atom:link href="${escapeXml(`${base}/api/walkthroughs/${params.id}/changelog.rss`)}" rel="self" type="application/rss+xml"/>\n` +
    `    <language>en-gb</language>\n` +
    `    <lastBuildDate>${lastBuild}</lastBuildDate>\n` +
    items +
    "\n  </channel>\n" +
    "</rss>\n";

  return new NextResponse(xml, {
    status: 200,
    headers: {
      "Content-Type": "application/rss+xml; charset=utf-8",
      "Cache-Control": "public, max-age=120, stale-while-revalidate=600",
    },
  });
}
