// Plain-Markdown export of a walkthrough — title + step-by-step narration
// + canonical timestamps. Drop the URL into Claude / ChatGPT / Cursor and
// the LLM gets enough context to answer questions about the product.
//
// Mintlify-parity: the public URL pattern is `<docs URL>.md`; the request
// is rewritten by next.config.js to land here.

import "server-only";
import { promises as fs } from "fs";
import path from "path";
import { NextResponse } from "next/server";
import { isValidWalkthroughId } from "@/lib/ids";
import { loadWalkthrough } from "@/lib/fs";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const REPO_ROOT = path.resolve(process.cwd(), "../..");
const WALKTHROUGHS_DIR = path.join(REPO_ROOT, "walkthroughs");

interface TimingDoc {
  duration_ms: number;
  steps: Array<{ step_id: string; start_ms: number; end_ms: number }>;
}

function fmtTs(ms: number): string {
  const totalSec = Math.max(0, Math.floor(ms / 1000));
  const m = Math.floor(totalSec / 60);
  const s = totalSec % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

function dashboardBase(req: Request): string {
  const env =
    process.env.NEXT_PUBLIC_DASHBOARD_URL ?? process.env.PUBLIC_DASHBOARD_URL;
  if (env) return env.replace(/\/$/, "");
  try {
    const u = new URL(req.url);
    return `${u.protocol}//${u.host}`;
  } catch {
    return "http://localhost:3000";
  }
}

export async function GET(
  req: Request,
  { params }: { params: { id: string } },
) {
  if (!isValidWalkthroughId(params.id)) {
    return NextResponse.json({ error: "invalid_id" }, { status: 400 });
  }

  let walkthrough;
  try {
    walkthrough = await loadWalkthrough(params.id);
  } catch {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }

  // Step-level timing if the continuous narration take has been built;
  // otherwise we synthesise from declared durations (same fallback shape
  // as /api/walkthroughs/[id]/transcript).
  let timing: TimingDoc | null = null;
  try {
    const raw = await fs.readFile(
      path.join(WALKTHROUGHS_DIR, params.id, "narration.timing.json"),
      "utf8",
    );
    timing = JSON.parse(raw) as TimingDoc;
  } catch {
    /* ignore */
  }
  const stepTiming = new Map<string, { start_ms: number; end_ms: number }>();
  if (timing) {
    for (const t of timing.steps) {
      stepTiming.set(t.step_id, { start_ms: t.start_ms, end_ms: t.end_ms });
    }
  } else {
    let cursor = 0;
    for (const s of walkthrough.steps) {
      stepTiming.set(s.id, { start_ms: cursor, end_ms: cursor + s.duration_ms });
      cursor += s.duration_ms;
    }
  }

  const totalMs = walkthrough.steps.reduce((n, s) => n + s.duration_ms, 0);
  const product = walkthrough.target_app.repo.split("/")[1] ?? walkthrough.id;
  const base = dashboardBase(req);
  const videoUrl = `${base}/walkthroughs/${params.id}/takes/master/master.mp4`;
  const captionsUrl = `${base}/api/walkthroughs/${params.id}/captions`;

  const lines: string[] = [];
  lines.push(`# A tour of ${product}`);
  lines.push("");
  lines.push(
    `Walkthrough _${walkthrough.id}_ · v${walkthrough.version} · ` +
      `${walkthrough.steps.length} steps · ${(totalMs / 1000).toFixed(0)} seconds · ` +
      `narrated by ${walkthrough.brand.voice_name}.`,
  );
  lines.push("");
  lines.push(`Source: \`${walkthrough.target_app.repo}\` · Dev URL: ${walkthrough.target_app.dev_url}`);
  lines.push("");
  lines.push(`Master video: ${videoUrl}`);
  lines.push(`Captions (WebVTT): ${captionsUrl}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (let i = 0; i < walkthrough.steps.length; i++) {
    const step = walkthrough.steps[i];
    const t = stepTiming.get(step.id);
    const ts = t ? fmtTs(t.start_ms) : `${i + 1}`;
    lines.push(`## ${i + 1}. ${step.title} _(${ts})_`);
    lines.push("");
    lines.push(step.narration);
    lines.push("");

    if (step.actions.length > 0) {
      lines.push("**Actions:**");
      for (const action of step.actions) {
        const kind = action.kind;
        const detail =
          kind === "goto"
            ? action.url
            : kind === "click" || kind === "hover"
              ? action.selector
              : kind === "fill"
                ? `${action.selector} = ${JSON.stringify(action.value)}`
                : kind === "wait"
                  ? `${action.ms}ms`
                  : kind === "scroll"
                    ? `${action.ms}px`
                    : kind === "press"
                      ? action.value
                      : "";
        lines.push(`- \`${kind}\` ${detail ?? ""}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push(
    `Generated by Foley · auto-maintained from \`${walkthrough.target_app.repo}\`'s pull requests.`,
  );
  lines.push("");

  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, max-age=120, stale-while-revalidate=600",
    },
  });
}
