"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { TranscriptPanel } from "@/components/TranscriptPanel";

interface MasterBackup {
  id: string;
  ts: string;
  promoted_from: string | null;
  master_sha256: string | null;
  size_bytes: number | null;
}

interface TakeChoice {
  id: string;
  pr_title: string | null;
  status: string;
  created_at: string;
}

interface Props {
  walkthroughId: string;
  totalDurationMs: number;
  masterSha?: string | null;
  promotedFrom?: string | null;
  videoUrl: string;
  takeOptions: TakeChoice[];
}

export function MasterCard({
  walkthroughId,
  totalDurationMs,
  masterSha,
  promotedFrom,
  videoUrl,
  takeOptions,
}: Props) {
  const router = useRouter();
  const [picking, setPicking] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [backups, setBackups] = useState<MasterBackup[]>([]);
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    if (!historyOpen) return;
    void fetch(`/api/walkthroughs/${walkthroughId}/master/history`)
      .then((r) => r.json())
      .then((j) => setBackups(j.backups ?? []))
      .catch(() => setBackups([]));
  }, [historyOpen, walkthroughId]);

  async function promote(takeId: string) {
    if (!confirm(`Promote ${takeId} to master? The current master will be archived.`)) return;
    setBusyId(takeId);
    try {
      const res = await fetch(`/api/walkthroughs/${walkthroughId}/master`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ take_id: takeId }),
      });
      const json = await res.json();
      if (!res.ok) {
        alert(json.error ?? "Promote failed");
      } else {
        setPicking(false);
        router.refresh();
      }
    } finally {
      setBusyId(null);
    }
  }

  return (
    <div className="sticky sticky-sky">
      <div style={{ display: "flex", alignItems: "baseline", gap: 8, marginBottom: 12 }}>
        <h2 style={{ margin: 0 }}>Master</h2>
        <button
          type="button"
          className="brand-edit-btn"
          onClick={() => setPicking((p) => !p)}
          style={{ marginLeft: "auto" }}
        >
          {picking ? "Cancel" : "Change master"}
        </button>
      </div>

      {/* Cache-bust the player when the master swaps so the user sees the new clip. */}
      <video
        ref={videoRef}
        controls
        preload="metadata"
        src={`${videoUrl}?t=${masterSha ?? "x"}`}
        key={masterSha ?? videoUrl}
        crossOrigin="anonymous"
      >
        {/* Captions are lazily generated by /api/walkthroughs/[id]/captions —
            the request 404s if narration.timing.json is missing, in which
            case the browser silently shows no captions track. */}
        <track
          kind="subtitles"
          srcLang="en"
          label="English"
          src={`/api/walkthroughs/${walkthroughId}/captions`}
          default={false}
        />
      </video>

      <TranscriptPanel walkthroughId={walkthroughId} videoRef={videoRef} />

      <div className="meta">
        {(totalDurationMs / 1000).toFixed(1)}s
        {masterSha ? <> · sha {masterSha.slice(0, 12)}…</> : null}
        {promotedFrom ? (
          <span style={{ marginLeft: 8, color: "var(--muted)" }}>
            ← from <strong>{promotedFrom}</strong>
          </span>
        ) : null}
      </div>

      <div style={{ marginTop: 12, display: "flex", gap: 6, flexWrap: "wrap" }}>
        <Link href={`/takes/master?wt=${walkthroughId}`} className="btn-secondary">Open in editor</Link>
        <button
          type="button"
          className="brand-edit-btn"
          onClick={() => setHistoryOpen((v) => !v)}
        >
          {historyOpen ? "Hide history" : "History"}
        </button>
      </div>
      {historyOpen ? (
        <div className="master-picker" style={{ marginTop: 10 }}>
          <div className="master-picker-label">Previous masters</div>
          {backups.length === 0 ? (
            <p style={{ color: "var(--muted)", fontSize: 13 }}>
              No backups yet — every promotion archives the prior master here.
            </p>
          ) : (
            <ul>
              {backups.map((b) => (
                <li key={b.id}>
                  <button
                    type="button"
                    className="master-picker-row"
                    onClick={() => promote(b.id)}
                    disabled={busyId !== null}
                    title={b.master_sha256 ?? ""}
                  >
                    <span className="mono">{b.id.replace("master.prev-", "").slice(0, 19)}</span>
                    <span className="title">
                      {b.promoted_from ? `was ${b.promoted_from}` : "(direct master)"}
                      {b.master_sha256 ? ` · sha ${b.master_sha256.slice(0, 8)}…` : ""}
                      {b.size_bytes ? ` · ${(b.size_bytes / (1024 * 1024)).toFixed(1)} MB` : ""}
                    </span>
                    <span className="cta">
                      {busyId === b.id ? "Restoring…" : "Restore →"}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      ) : null}

      {picking ? (
        <div className="master-picker">
          <div className="master-picker-label">Promote a take to master</div>
          {takeOptions.length === 0 ? (
            <p style={{ color: "var(--muted)", fontSize: 13 }}>No other takes yet.</p>
          ) : (
            <ul>
              {takeOptions.map((t) => (
                <li key={t.id}>
                  <button
                    type="button"
                    className="master-picker-row"
                    onClick={() => promote(t.id)}
                    disabled={busyId !== null}
                  >
                    <span className="mono">{t.id}</span>
                    <span className={`status status-${t.status}`}>{t.status}</span>
                    <span className="title">{t.pr_title ?? "—"}</span>
                    <span className="cta">
                      {busyId === t.id ? "Promoting…" : "Promote →"}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      ) : null}
    </div>
  );
}
