// One YAML, two outputs.
// The same Walkthrough that drives the video also renders here as a
// scrollable, on-brand documentation page. No CMS, no editor — just the
// canonical Steps, on-brand.

import Link from "next/link";
import { notFound } from "next/navigation";
import { listTakes, loadWalkthrough, stepFramePath, takePublicPath } from "@/lib/fs";

export const dynamic = "force-dynamic";

export default async function DocsPage({ params }: { params: { walkthrough: string } }) {
  let walkthrough, masterTakeId;
  try {
    walkthrough = await loadWalkthrough(params.walkthrough);
    const takes = await listTakes(params.walkthrough);
    masterTakeId = takes.find((t) => t.id === "master")?.id ?? takes[0]?.id;
  } catch {
    notFound();
  }
  if (!masterTakeId) notFound();

  const totalMs = walkthrough.steps.reduce((n, s) => n + s.duration_ms, 0);

  return (
    <main
      className="docs"
      style={{
        // Brand variables drive the page palette.
        ["--brand-bg" as string]: walkthrough.brand.palette_bg,
        ["--brand-fg" as string]: walkthrough.brand.palette_fg,
        ["--brand-accent" as string]: walkthrough.brand.palette_accent,
      }}
    >
      <header className="docs-hero">
        <div className="brand-band" />
        <div className="docs-hero-inner">
          <p className="docs-eyebrow">Walkthrough · v{walkthrough.version}</p>
          <h1 className="docs-title">A tour of {walkthrough.target_app.repo.split("/")[1]}</h1>
          <p className="docs-meta">
            {walkthrough.steps.length} steps · {(totalMs / 1000).toFixed(0)}s · narrated by {walkthrough.brand.voice_name}
          </p>
          <Link href={`/takes/${masterTakeId}`} className="docs-cta">
            Watch the video →
          </Link>
        </div>
      </header>

      <ol className="docs-steps">
        {walkthrough.steps.map((step, i) => (
          <li key={step.id} className="docs-step">
            <div className="docs-step-num">{String(i + 1).padStart(2, "0")}</div>
            <div className="docs-step-body">
              <h2>{step.title}</h2>
              <p className="narration">{step.narration}</p>
              <video
                src={takePublicPath(params.walkthrough, masterTakeId, `segments/${step.id}.mp4`)}
                poster={stepFramePath(params.walkthrough, step.id)}
                muted
                playsInline
                preload="none"
                controls
              />
              <p className="docs-step-meta">{(step.duration_ms / 1000).toFixed(1)}s</p>
            </div>
          </li>
        ))}
      </ol>

      <footer className="docs-footer">
        <p>Generated by Foley from one YAML spec.</p>
        <p className="muted">Brand voice: {walkthrough.brand.voice_name} · Locked at the walkthrough level.</p>
      </footer>
    </main>
  );
}
