import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";
import { loadWalkthrough, loadManifest, listTakes } from "@/lib/fs";
import { isValidWalkthroughId } from "@/lib/ids";

export const dynamic = "force-dynamic";

const REPO_ROOT = path.resolve(process.cwd(), "../..");

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export async function GET(req: NextRequest): Promise<Response> {
  const id = req.nextUrl.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });
  if (!isValidWalkthroughId(id)) {
    return NextResponse.json({ error: "invalid_id" }, { status: 400 });
  }

  let wt;
  try {
    wt = await loadWalkthrough(id);
  } catch {
    return NextResponse.json({ error: "walkthrough not found" }, { status: 404 });
  }
  await listTakes(id).catch(() => []);
  const manifest = await loadManifest(id, "master").catch(() => null);

  // Embed the master.mp4 as a base64 data URL — single-file site.
  const masterPath = path.join(REPO_ROOT, "walkthroughs", id, "takes", "master", "master.mp4");
  let videoDataUrl = "";
  try {
    const buf = await readFile(masterPath);
    videoDataUrl = `data:video/mp4;base64,${buf.toString("base64")}`;
  } catch {
    /* leave empty — page still renders */
  }

  const display = (wt as { display_name?: string }).display_name ?? id;
  const totalDur = wt.steps.reduce((n, s) => n + s.duration_ms, 0);
  const totalSec = Math.round(totalDur / 1000);

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(display)} — Foley walkthrough</title>
<meta name="description" content="${escapeHtml(wt.steps[0]?.narration ?? "Auto-generated walkthrough")}">
<style>
  * { box-sizing: border-box; }
  body { margin: 0; font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "SF Pro Text", system-ui, sans-serif; background: #faf6ee; color: #1d1d1f; line-height: 1.55; }
  .wrap { max-width: 920px; margin: 0 auto; padding: 56px 24px 80px; }
  .top { display: flex; align-items: center; justify-content: space-between; margin-bottom: 28px; }
  .brand { display: inline-flex; align-items: center; gap: 8px; font-weight: 700; }
  .brand-dot { width: 16px; height: 16px; border-radius: 5px; background: linear-gradient(135deg, #f5b94a, #e08c2e); }
  h1 { font-size: 42px; letter-spacing: -0.8px; margin: 8px 0 8px; }
  .meta { color: rgba(0,0,0,0.55); font-size: 13.5px; margin-bottom: 22px; }
  video { width: 100%; border-radius: 16px; box-shadow: 0 24px 50px rgba(0,0,0,0.18); background: #000; aspect-ratio: 16/9; }
  .steps { margin-top: 36px; display: grid; gap: 14px; }
  .step { background: #fff; border: 1px solid rgba(0,0,0,0.06); border-radius: 14px; padding: 16px 18px; }
  .step h3 { margin: 0 0 4px; font-size: 16px; }
  .step p { margin: 0; color: rgba(0,0,0,0.65); font-size: 14px; }
  .step-row { display: flex; gap: 14px; align-items: flex-start; }
  .step-num { color: rgba(0,0,0,0.4); font-size: 12px; font-feature-settings: "tnum"; min-width: 26px; }
  footer { margin-top: 50px; text-align: center; color: rgba(0,0,0,0.5); font-size: 12px; }
  footer a { color: inherit; }
</style>
</head>
<body>
  <div class="wrap">
    <div class="top">
      <div class="brand"><span class="brand-dot"></span> Foley</div>
      <div style="font-size: 12px; color: rgba(0,0,0,0.45)">walkthrough · self-hosted export</div>
    </div>
    <h1>${escapeHtml(display)}</h1>
    <div class="meta">${wt.steps.length} steps · ${totalSec}s · narrated by ${escapeHtml(wt.brand.voice_name)}${manifest ? ` · master <code>${manifest.master_sha256.slice(0, 7)}</code>` : ""}</div>
    ${videoDataUrl ? `<video controls poster="" src="${videoDataUrl}"></video>` : "<p>(master video not available in this export)</p>"}
    <div class="steps">
      ${wt.steps
        .map(
          (s, i) => `<div class="step"><div class="step-row"><div class="step-num">${String(i + 1).padStart(2, "0")}</div><div><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.narration)}</p></div></div></div>`,
        )
        .join("\n")}
    </div>
    <footer>
      Auto-generated by <a href="https://foley.app">Foley</a> · maintained on every PR
    </footer>
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${id}-foley.html"`,
    },
  });
}
